from __future__ import annotations

from pathlib import Path
from typing import Any
import json
import tkinter as tk
from tkinter import ttk

from ..base_tab import BaseTab
from ..ui_helpers import set_tree_rows


FAIL_DECISIONS = {"REJECTED_BACKTEST_FAILED", "REJECTED_NO_TUNABLE_PARAMS"}


class ExplorerSummaryTab(BaseTab):
    """Explorer summary and loop review.

    Reads compact summary + audit metadata generated by the Explorer runner.
    This UI is read-only and strategy-scoped by active Setup strategy.
    """

    tab_key = "explorer_summary"
    tab_title = "Explorer Summary"

    def __init__(self, master: tk.Misc, context: Any) -> None:
        super().__init__(master, context)
        self.summary_path = context.app_dir.parent / "explorer_reports" / "latest_summary.json"
        self.audit_dir = context.app_dir.parent / "explorer_reports" / "runs"
        self.presets_path = context.app_dir / "launcher_v2" / "config" / "presets.json"
        self._refresh_after_id: str | None = None
        self._loop_row_map: dict[str, dict[str, Any]] = {}
        self._build_ui()
        self.refresh()

    def _build_ui(self) -> None:
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(2, weight=1)

        header = ttk.LabelFrame(self, text="Last Explorer Loop")
        header.grid(row=0, column=0, sticky="ew", padx=8, pady=8)
        for col in (1, 3, 5, 7):
            header.grid_columnconfigure(col, weight=1)

        self.strategy_var = tk.StringVar(value="-")
        self.loop_var = tk.StringVar(value="-")
        self.target_var = tk.StringVar(value="-")
        self.breadth_var = tk.StringVar(value="-")
        self.training_var = tk.StringVar(value="-")
        self.validation_count_var = tk.StringVar(value="-")
        self.decision_var = tk.StringVar(value="-")
        self.changed_var = tk.StringVar(value="-")

        ttk.Label(header, text="Active strategy").grid(row=0, column=0, sticky="w", padx=8, pady=4)
        ttk.Label(header, textvariable=self.strategy_var).grid(row=0, column=1, columnspan=7, sticky="ew", padx=8, pady=4)

        fields = [
            ("Loop", self.loop_var),
            ("Target", self.target_var),
            ("Breadth", self.breadth_var),
            ("Training", self.training_var),
            ("Validation windows", self.validation_count_var),
            ("Decision", self.decision_var),
            ("Changed params", self.changed_var),
        ]
        for idx, (label, variable) in enumerate(fields):
            row = 1 + (idx // 4)
            col = (idx % 4) * 2
            ttk.Label(header, text=label).grid(row=row, column=col, sticky="w", padx=8, pady=4)
            ttk.Label(header, textvariable=variable).grid(row=row, column=col + 1, sticky="ew", padx=8, pady=4)

        loops_frame = ttk.LabelFrame(self, text="Run Loop History")
        loops_frame.grid(row=1, column=0, sticky="nsew", padx=8, pady=(0, 8))
        loops_frame.grid_columnconfigure(0, weight=1)
        loops_frame.grid_rowconfigure(0, weight=1)
        loop_columns = ("loop", "target", "breadth", "decision", "accepted", "final_delta", "changed")
        self.loop_tree = ttk.Treeview(loops_frame, columns=loop_columns, show="headings", height=7)
        headings = {
            "loop": "Loop",
            "target": "Target",
            "breadth": "Breadth",
            "decision": "Decision",
            "accepted": "Accepted",
            "final_delta": "Final score delta",
            "changed": "Changed params",
        }
        for name in loop_columns:
            self.loop_tree.heading(name, text=headings[name])
            width = 100 if name in {"loop", "accepted", "changed", "breadth"} else (210 if name == "target" else 170)
            self.loop_tree.column(name, width=width, anchor="w", stretch=name in {"target", "decision"})
        self.loop_tree.grid(row=0, column=0, sticky="nsew", padx=(8, 0), pady=(8, 0))
        loop_scroll_y = ttk.Scrollbar(loops_frame, orient="vertical", command=self.loop_tree.yview)
        loop_scroll_y.grid(row=0, column=1, sticky="ns", pady=(8, 0), padx=(4, 8))
        loop_scroll_x = ttk.Scrollbar(loops_frame, orient="horizontal", command=self.loop_tree.xview)
        loop_scroll_x.grid(row=1, column=0, sticky="ew", padx=(8, 0), pady=(4, 8))
        self.loop_tree.configure(yscrollcommand=loop_scroll_y.set, xscrollcommand=loop_scroll_x.set)
        self.loop_tree.bind("<<TreeviewSelect>>", self._on_loop_select)

        notebook = ttk.Notebook(self)
        notebook.grid(row=2, column=0, sticky="nsew", padx=8, pady=(0, 8))
        self.score_tree = self._make_tree(notebook, "Champion vs Challenger", ["Metric", "Champion", "Challenger", "Delta", "Role"])
        self.validation_tree = self._make_tree(
            notebook,
            "Validation Breakdown",
            ["Window", "Regime", "Role", "Objective", "Max DD %", "Score", "Delta score", "Guard"],
        )
        self.evolution_tree = self._make_tree(
            notebook,
            "Accepted Param Evolution",
            ["Accepted at", "Run/Loop", "Target", "Breadth", "Param", "Space", "Old", "New", "Delta"],
        )

        footer = ttk.Frame(self, style="App.TFrame")
        footer.grid(row=3, column=0, sticky="ew", padx=8, pady=(0, 8))
        ttk.Button(footer, text="Refresh", command=self.refresh).pack(side="left")

    def _make_tree(self, notebook: ttk.Notebook, title: str, columns: list[str]) -> ttk.Treeview:
        frame = ttk.Frame(notebook)
        frame.grid_columnconfigure(0, weight=1)
        frame.grid_rowconfigure(0, weight=1)
        tree = ttk.Treeview(frame, columns=columns, show="headings")
        tree.column("#0", width=0, stretch=False)
        tree["displaycolumns"] = columns
        width_overrides: dict[str, int] = {}
        stretch_columns: set[str] = set()
        if title == "Validation Breakdown":
            width_overrides = {
                "Window": 220,
                "Regime": 95,
                "Role": 95,
                "Objective": 90,
                "Max DD %": 85,
                "Score": 90,
                "Delta score": 90,
                "Guard": 85,
            }
            stretch_columns = {"Window"}
        elif title == "Champion vs Challenger":
            width_overrides = {
                "Metric": 95,
                "Champion": 120,
                "Challenger": 120,
                "Delta": 110,
                "Role": 95,
            }
            stretch_columns = set()
        elif title == "Accepted Param Evolution":
            width_overrides = {
                "Accepted at": 145,
                "Run/Loop": 85,
                "Target": 210,
                "Breadth": 85,
                "Param": 220,
                "Space": 75,
                "Old": 115,
                "New": 115,
                "Delta": 95,
            }
            stretch_columns = {"Target", "Param"}
        for column in columns:
            tree.heading(column, text=column, anchor="w")
            if column in width_overrides:
                width = int(width_overrides[column])
            elif column in {"Window", "Target", "Param"}:
                width = 240
            elif column in {"Accepted at", "Old", "New", "Delta", "Metric"}:
                width = 145
            else:
                width = 120
            tree.column(column, width=width, minwidth=width, anchor="w", stretch=column in stretch_columns)
        tree.grid(row=0, column=0, sticky="nsew")
        scrollbar_y = ttk.Scrollbar(frame, orient="vertical", command=tree.yview)
        scrollbar_y.grid(row=0, column=1, sticky="ns")
        scrollbar_x = ttk.Scrollbar(frame, orient="horizontal", command=tree.xview)
        scrollbar_x.grid(row=1, column=0, sticky="ew")
        tree.configure(yscrollcommand=scrollbar_y.set, xscrollcommand=scrollbar_x.set)
        notebook.add(frame, text=title)
        return tree

    def _read_json(self, path: Path) -> dict[str, Any]:
        if not path.exists():
            return {}
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return {}
        return payload if isinstance(payload, dict) else {}

    def _load_preset(self, name: str) -> dict[str, Any]:
        payload = self._read_json(self.presets_path)
        preset = payload.get(name) if isinstance(payload, dict) else {}
        return preset if isinstance(preset, dict) else {}

    def _strategy_context(self) -> tuple[str, str]:
        common = self.context.registry.get("common")
        if common is not None:
            try:
                state = common.get_state()
            except Exception:
                state = {}
            strategy_file = str(state.get("strategy_file") or "")
            strategy_class = str(state.get("strategy_class") or "")
            if strategy_file and strategy_class:
                return strategy_file, strategy_class
        for preset_name in ("LauncherV2-auto", "LauncherV2-current", "BackTest2021-26"):
            preset = self._load_preset(preset_name)
            strategy_file = str(preset.get("strategy_file") or "")
            strategy_class = str(preset.get("strategy_class") or "")
            if strategy_file and strategy_class:
                return strategy_file, strategy_class
        return "", ""

    def _normalize_path(self, path_value: str) -> str:
        text = str(path_value or "").strip()
        if not text:
            return ""
        path = Path(text).expanduser()
        if not path.is_absolute():
            base = Path(str(self.context.shared.project_root.get() or self.context.app_dir))
            path = (base / path).resolve()
        try:
            return str(path.resolve()).lower()
        except Exception:
            return str(path).lower()

    def _strategy_matches(self, candidate_file: str, candidate_class: str, active_file: str, active_class: str) -> bool:
        active_file_norm = self._normalize_path(active_file)
        active_class_norm = str(active_class or "").strip().lower()
        if not active_file_norm or not active_class_norm:
            return True
        candidate_file_norm = self._normalize_path(candidate_file)
        candidate_class_norm = str(candidate_class or "").strip().lower()
        return bool(candidate_file_norm and candidate_class_norm and candidate_file_norm == active_file_norm and candidate_class_norm == active_class_norm)

    def _strategy_display(self, strategy_file: str, strategy_class: str) -> str:
        if not strategy_file or not strategy_class:
            return "No active strategy selected in Setup"
        return f"{Path(strategy_file).name} :: {strategy_class}"

    def _latest_summary(self) -> dict[str, Any]:
        return self._read_json(Path(self.summary_path))

    def _strategy_from_audit(self, audit_payload: dict[str, Any]) -> tuple[str, str]:
        strategy_file = str(audit_payload.get("strategy_file") or "")
        strategy_class = str(audit_payload.get("strategy_class") or "")
        if strategy_file and strategy_class:
            return strategy_file, strategy_class

        loops = audit_payload.get("loops") if isinstance(audit_payload.get("loops"), list) else []
        for entry in loops:
            if not isinstance(entry, dict):
                continue
            summary = entry.get("summary") if isinstance(entry.get("summary"), dict) else {}
            strategy_file = str(summary.get("strategy_file") or "")
            strategy_class = str(summary.get("strategy_class") or "")
            if strategy_file and strategy_class:
                return strategy_file, strategy_class

        args = audit_payload.get("args") if isinstance(audit_payload.get("args"), dict) else {}
        preset_file = Path(str(args.get("preset_file") or "")).expanduser()
        preset_name = str(args.get("preset") or "")
        if preset_file and preset_name and preset_file.exists():
            payload = self._read_json(preset_file)
            preset = payload.get(preset_name) if isinstance(payload, dict) else {}
            if isinstance(preset, dict):
                strategy_file = str(preset.get("strategy_file") or "")
                strategy_class = str(preset.get("strategy_class") or "")
                if strategy_file and strategy_class:
                    return strategy_file, strategy_class
        return "", ""

    def _resolve_audit_file(self, summary: dict[str, Any], active_file: str, active_class: str) -> Path | None:
        run_id = str(summary.get("run_id") or "").strip()
        if run_id:
            candidate = self.audit_dir / f"{run_id}.json"
            if candidate.exists():
                if self._strategy_matches(
                    str(summary.get("strategy_file") or ""),
                    str(summary.get("strategy_class") or ""),
                    active_file,
                    active_class,
                ):
                    return candidate
                payload = self._read_json(candidate)
                cand_file, cand_class = self._strategy_from_audit(payload)
                if self._strategy_matches(cand_file, cand_class, active_file, active_class):
                    return candidate

        if not self.audit_dir.exists():
            return None
        candidates = [path for path in self.audit_dir.glob("*.json") if path.is_file()]
        candidates.sort(key=lambda item: item.stat().st_mtime, reverse=True)
        for candidate in candidates:
            payload = self._read_json(candidate)
            cand_file, cand_class = self._strategy_from_audit(payload)
            if self._strategy_matches(cand_file, cand_class, active_file, active_class):
                return candidate
        return None

    def _build_loop_payload(self, loop_entry: dict[str, Any]) -> dict[str, Any]:
        summary = loop_entry.get("summary")
        if isinstance(summary, dict):
            payload = dict(summary)
            payload.setdefault("loop_index", loop_entry.get("loop_index"))
            payload.setdefault("decision_code", loop_entry.get("decision_code"))
            payload.setdefault("target_label", (loop_entry.get("target") or {}).get("target_label"))
            payload.setdefault("error", loop_entry.get("error"))
            return payload
        comparison = loop_entry.get("comparison")
        if isinstance(comparison, dict):
            return {
                "loop_index": loop_entry.get("loop_index"),
                "loop_total": "",
                "target_label": ((loop_entry.get("target") or {}).get("target_label") or ""),
                "search_breadth": ((loop_entry.get("target") or {}).get("search_breadth") or ""),
                "training_windows": [loop_entry.get("training_window")] if isinstance(loop_entry.get("training_window"), dict) else [],
                "validation_windows": list(loop_entry.get("validation_windows") or []),
                "decision_code": comparison.get("decision_code") or loop_entry.get("decision_code") or "",
                "accepted": bool(comparison.get("accepted", False)),
                "params_changed_count": 0,
                "champion": dict(comparison.get("champion") or {}),
                "challenger": dict(comparison.get("challenger") or {}),
                "delta": dict(comparison.get("delta") or {}),
                "score_table": [],
                "validation_breakdown": [],
                "error": loop_entry.get("error"),
            }
        return {
            "loop_index": loop_entry.get("loop_index"),
            "loop_total": "",
            "target_label": ((loop_entry.get("target") or {}).get("target_label") or ""),
            "search_breadth": ((loop_entry.get("target") or {}).get("search_breadth") or ""),
            "training_windows": [loop_entry.get("training_window")] if isinstance(loop_entry.get("training_window"), dict) else [],
            "validation_windows": list(loop_entry.get("validation_windows") or []),
            "decision_code": loop_entry.get("decision_code") or "",
            "accepted": False,
            "params_changed_count": 0,
            "champion": {},
            "challenger": {},
            "delta": {},
            "score_table": [],
            "validation_breakdown": [],
            "error": loop_entry.get("error"),
        }

    def _accepted_param_evolution(self, loops: list[dict[str, Any]]) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        for loop_entry in loops:
            if not isinstance(loop_entry, dict):
                continue
            summary = loop_entry.get("summary") if isinstance(loop_entry.get("summary"), dict) else {}
            comparison = loop_entry.get("comparison") if isinstance(loop_entry.get("comparison"), dict) else {}
            accepted = bool(summary.get("accepted")) if summary else bool(comparison.get("accepted"))
            if not accepted:
                continue
            changes = loop_entry.get("changes")
            if not isinstance(changes, list):
                continue
            loop_index = int(loop_entry.get("loop_index") or summary.get("loop_index") or 0)
            loop_total = summary.get("loop_total") if summary else ""
            target = (loop_entry.get("target") or {}).get("target_label") or summary.get("target_label") or ""
            breadth = (loop_entry.get("target") or {}).get("search_breadth") or summary.get("search_breadth") or ""
            accepted_at = str(summary.get("saved_at") or "")
            total_text = "∞" if str(loop_total).strip() == "0" else str(loop_total)
            loop_text = f"{loop_index}/{total_text}" if loop_total not in {"", None} else str(loop_index)
            for change in changes:
                if not isinstance(change, dict):
                    continue
                if not bool(change.get("changed")):
                    continue
                delta_value = change.get("delta")
                if not isinstance(delta_value, (int, float)):
                    delta_value = change.get("direction") or ""
                rows.append(
                    {
                        "accepted_at": accepted_at,
                        "run_loop": loop_text,
                        "target": str(target),
                        "breadth": str(breadth),
                        "param": str(change.get("param") or ""),
                        "space": str(change.get("space") or ""),
                        "old": change.get("previous"),
                        "new": change.get("new"),
                        "delta": delta_value,
                        "loop_index": loop_index,
                    }
                )
        rows.sort(key=lambda item: (int(item.get("loop_index") or 0), str(item.get("param") or "")))
        return rows

    def _load_loop_payloads(self, summary: dict[str, Any], active_file: str, active_class: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        audit_file = self._resolve_audit_file(summary, active_file, active_class)
        loops: list[dict[str, Any]] = []
        payloads: list[dict[str, Any]] = []
        if audit_file is not None:
            audit_payload = self._read_json(audit_file)
            loops = [entry for entry in (audit_payload.get("loops") or []) if isinstance(entry, dict)]
            payloads = [self._build_loop_payload(entry) for entry in loops]
            payloads = [item for item in payloads if isinstance(item, dict)]
            payloads.sort(key=lambda item: int(item.get("loop_index") or 0))
        if not payloads and summary:
            if self._strategy_matches(
                str(summary.get("strategy_file") or ""),
                str(summary.get("strategy_class") or ""),
                active_file,
                active_class,
            ):
                payloads = [dict(summary)]
        evolution = self._accepted_param_evolution(loops)
        for payload in payloads:
            payload["accepted_param_evolution"] = evolution
        return payloads, evolution

    def _render_loop_history(self, loop_payloads: list[dict[str, Any]]) -> str | None:
        selected = self.loop_tree.selection()
        selected_id = selected[0] if selected else None
        for item_id in self.loop_tree.get_children():
            self.loop_tree.delete(item_id)
        self._loop_row_map = {}
        selected_fallback: str | None = None
        for idx, payload in enumerate(loop_payloads):
            loop_index = int(payload.get("loop_index") or (idx + 1))
            item_id = f"loop_{idx}_{loop_index}"
            decision = str(payload.get("decision_code") or "")
            target = str(payload.get("target_label") or f"{payload.get('target_type', '')}:{payload.get('target_name', '')}")
            breadth = str(payload.get("search_breadth") or "")
            accepted = "yes" if bool(payload.get("accepted")) else "no"
            delta = (payload.get("delta") or {}).get("final_score", "")
            changed = payload.get("params_changed_count", "")
            self.loop_tree.insert("", tk.END, iid=item_id, values=(loop_index, target, breadth, decision, accepted, self._display(delta), changed))
            self._loop_row_map[item_id] = payload
            if decision not in FAIL_DECISIONS:
                selected_fallback = item_id
        if selected_id and selected_id in self._loop_row_map:
            self.loop_tree.selection_set(selected_id)
            return selected_id
        if selected_fallback is not None:
            self.loop_tree.selection_set(selected_fallback)
            return selected_fallback
        first = next(iter(self._loop_row_map.keys()), None)
        if first is not None:
            self.loop_tree.selection_set(first)
        return first

    @staticmethod
    def _display(value: Any) -> Any:
        if isinstance(value, float):
            return f"{value:.6f}"
        return value

    def _is_no_change_duplicate(self, data: dict[str, Any]) -> bool:
        try:
            changed_count = int(data.get("params_changed_count") or 0)
        except Exception:
            changed_count = 0
        if changed_count != 0:
            return False
        champion = data.get("champion") if isinstance(data.get("champion"), dict) else {}
        challenger = data.get("challenger") if isinstance(data.get("challenger"), dict) else {}
        if not champion or not challenger:
            return False
        fields = (
            "objective_total",
            "max_drawdown_pct",
            "drawdown_penalty_total",
            "final_score",
            "profit_total",
            "trade_count",
            "losing_window_count",
            "winrate",
        )
        return all(champion.get(field) == challenger.get(field) for field in fields)

    def _apply_summary(self, data: dict[str, Any], evolution: list[dict[str, Any]]) -> None:
        if not data:
            self.loop_var.set("-")
            self.target_var.set("No Explorer history for active strategy")
            self.breadth_var.set("-")
            self.training_var.set("-")
            self.validation_count_var.set("-")
            self.decision_var.set("-")
            self.changed_var.set("-")
            set_tree_rows(self.score_tree, [])
            set_tree_rows(self.validation_tree, [])
            set_tree_rows(self.evolution_tree, [])
            return

        target = data.get("target_label") or f"{data.get('target_type', '')}:{data.get('target_name', '')}"
        training = ", ".join(str(item.get("name") or item.get("timerange") or "") for item in (data.get("training_windows") or []) if isinstance(item, dict))
        validation = [item for item in (data.get("validation_windows") or []) if isinstance(item, dict)]
        loop_total = data.get("loop_total", "-")
        loop_total_text = "∞" if str(loop_total).strip() == "0" else str(loop_total)
        self.loop_var.set(f"{data.get('loop_index', '-')} / {loop_total_text}")
        self.target_var.set(str(target or "-"))
        self.breadth_var.set(str(data.get("search_breadth") or "-"))
        self.training_var.set(training or "-")
        self.validation_count_var.set(str(len(validation)))
        self.decision_var.set(str(data.get("decision_code") or "-"))
        self.changed_var.set(str(data.get("params_changed_count") if data.get("params_changed_count") is not None else "-"))

        no_change_duplicate = self._is_no_change_duplicate(data)
        score_rows = []
        if not no_change_duplicate:
            for row in data.get("score_table") or []:
                if isinstance(row, dict):
                    score_rows.append((row.get("metric", ""), self._display(row.get("champion")), self._display(row.get("challenger")), self._display(row.get("delta")), row.get("role", "")))
        if not score_rows:
            champion = data.get("champion") or {}
            challenger = data.get("challenger") or {}
            delta = data.get("delta") or {}
            score_rows = [
                ("Objective total", self._display(champion.get("objective_total", "")), self._display(challenger.get("objective_total", "")), self._display(delta.get("objective_total", "")), "Score"),
                ("Max drawdown %", self._display(champion.get("max_drawdown_pct", "")), self._display(challenger.get("max_drawdown_pct", "")), self._display(delta.get("max_drawdown_pct", "")), "Hard guard"),
                ("Drawdown penalty", self._display(champion.get("drawdown_penalty_total", "")), self._display(challenger.get("drawdown_penalty_total", "")), self._display(delta.get("drawdown_penalty_total", "")), "Score"),
                ("Final score", self._display(champion.get("final_score", "")), self._display(challenger.get("final_score", "")), self._display(delta.get("final_score", "")), "Decision"),
                ("Profit total", self._display(champion.get("profit_total", "")), self._display(challenger.get("profit_total", "")), self._display(delta.get("profit_total", "")), "Info"),
                ("Trade count", champion.get("trade_count", ""), challenger.get("trade_count", ""), delta.get("trade_count", ""), "Info"),
                ("Losing windows", champion.get("losing_window_count", ""), challenger.get("losing_window_count", ""), delta.get("losing_window_count", ""), "Info"),
                ("Winrate", self._display(champion.get("winrate", "")), self._display(challenger.get("winrate", "")), self._display(delta.get("winrate", "")), "Info"),
            ]
        if no_change_duplicate:
            score_rows = [
                (row[0], row[1], "No parameter changes" if idx == 0 else "", "", row[4])
                for idx, row in enumerate(score_rows)
            ]
        error_text = str(data.get("error") or "").strip()
        if no_change_duplicate and not error_text:
            error_text = "Hyperopt returned no parameter changes; challenger was not a distinct candidate."
        if error_text:
            score_rows.append(("Review note", error_text, "", "", str(data.get("decision_code") or "")))
        set_tree_rows(self.score_tree, score_rows)

        validation_rows: list[tuple[Any, ...]] = []
        for item in (data.get("validation_breakdown") or []):
            if not isinstance(item, dict):
                continue
            window = item.get("window") or item.get("name") or ""
            regime = item.get("regime") or ""
            validation_rows.append(
                (
                    window,
                    regime,
                    "Champion",
                    self._display(item.get("champion_objective", "")),
                    self._display(item.get("champion_max_drawdown_pct", "")),
                    self._display(item.get("champion_score", "")),
                    "",
                    "",
                )
            )
            if no_change_duplicate:
                validation_rows.append((window, regime, "Challenger", "No parameter changes", "", "", "", ""))
            else:
                validation_rows.append(
                    (
                        window,
                        regime,
                        "Challenger",
                        self._display(item.get("challenger_objective", "")),
                        self._display(item.get("challenger_max_drawdown_pct", "")),
                        self._display(item.get("challenger_score", "")),
                        self._display(item.get("delta_score", "")),
                        item.get("guard", ""),
                    )
                )
        if not validation_rows and error_text:
            validation_rows.append(("Explorer", "", "Error", error_text, "", "", "", str(data.get("decision_code") or "")))
        set_tree_rows(self.validation_tree, validation_rows)

        evolution_rows = [
            (
                item.get("accepted_at", ""),
                item.get("run_loop", ""),
                item.get("target", ""),
                item.get("breadth", ""),
                item.get("param", ""),
                item.get("space", ""),
                self._display(item.get("old")),
                self._display(item.get("new")),
                self._display(item.get("delta")),
            )
            for item in evolution
            if isinstance(item, dict)
        ]
        set_tree_rows(self.evolution_tree, evolution_rows)

    def refresh(self) -> None:
        active_file, active_class = self._strategy_context()
        self.strategy_var.set(self._strategy_display(active_file, active_class))
        summary = self._latest_summary()
        payloads, evolution = self._load_loop_payloads(summary, active_file, active_class)
        selected_item = self._render_loop_history(payloads)
        if selected_item and selected_item in self._loop_row_map:
            self._apply_summary(self._loop_row_map[selected_item], evolution)
        elif payloads:
            self._apply_summary(payloads[-1], evolution)
        else:
            self._apply_summary({}, evolution)

    def _on_loop_select(self, _event: tk.Event | None = None) -> None:
        selection = self.loop_tree.selection()
        if not selection:
            return
        item_id = selection[0]
        payload = self._loop_row_map.get(item_id)
        if payload is not None:
            evolution = payload.get("accepted_param_evolution")
            rows = evolution if isinstance(evolution, list) else []
            self._apply_summary(payload, rows)

    def _schedule_refresh(self) -> None:
        if self._refresh_after_id is not None:
            return
        self._refresh_after_id = self.after(250, self._refresh_from_output)

    def _refresh_from_output(self) -> None:
        self._refresh_after_id = None
        self.refresh()

    def on_app_event(self, event: str, payload: dict[str, Any]) -> None:
        if event != "process_output":
            return
        text = str(payload.get("text") or "")
        if "EXPLORER_STATUS_JSON" in text or "Explorer latest summary JSON" in text:
            self._schedule_refresh()

    def get_state(self) -> dict[str, Any]:
        selection = self.loop_tree.selection()
        return {"selected_loop_row": selection[0] if selection else ""}

    def set_state(self, state: dict[str, Any]) -> None:
        self.refresh()
        selected = str(state.get("selected_loop_row") or "")
        if selected and selected in self._loop_row_map:
            self.loop_tree.selection_set(selected)
            payload = self._loop_row_map[selected]
            evolution = payload.get("accepted_param_evolution")
            rows = evolution if isinstance(evolution, list) else []
            self._apply_summary(payload, rows)
