from __future__ import annotations

import argparse
from dataclasses import fields
from datetime import datetime, time
import json
from pathlib import Path
import subprocess
import sys
from typing import Any
from zoneinfo import ZoneInfo

from .entry_sieve_service import EntrySieveService, EntrySieveSettings


APP_DIR = Path(__file__).resolve().parents[2]
REPO_ROOT = APP_DIR.parents[1]
RUNTIME_DIR = APP_DIR / "launcher_v2" / "runtime" / "entry_sieve"
STATE_FILE = RUNTIME_DIR / "queues" / "sieve3_exit_autobatch_state.json"
BATCH_FILE = RUNTIME_DIR / "queues" / "sieve3_exit_autobatches.json"
CORE_PAIRS = [
    "BTC/USDT:USDT",
    "ETH/USDT:USDT",
    "ADA/USDT:USDT",
    "SOL/USDT:USDT",
    "BNB/USDT:USDT",
]
PRESEED_RESULT_JOB_IDS = [
    "20260613T_repaired_sieve3_exit_multimetric_fresh40_10pairs_longcycle_300epoch_2win_2seed_cores20",
    "20260614T0440_repaired_sieve3_exit_multimetric_fresh40_5pairs_resume_from_10pair_rows28_300epoch_2win_2seed_cores20",
]
LOW_POWER_CORES = 6
HIGH_POWER_CORES = 16
BATCH_SIZE = 10
PATTERN_TOKENS = (
    "complete_pattern",
    "_pattern_",
    "geometry",
    "continuation_flag",
    "continuation_pennant",
    "reversal",
    "wolfe",
    "triangle",
    "wedge",
    "rectangle",
    "channel",
    "compression",
    "flag",
    "pennant",
    "head_shoulders",
    "_hs_",
    "_ihs_",
    "double_top",
    "double_bottom",
    "triple_top",
    "triple_bottom",
    "multi_peak",
)


def _load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return default


def _save_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _strategy_class_name(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("class ") and "(" in stripped:
            return stripped.split("class ", 1)[1].split("(", 1)[0].strip()
    return ""


def _chunks(items: list[Path], size: int) -> list[list[Path]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def _batch_number(batch_id: str) -> int:
    try:
        return int(str(batch_id).rsplit("_", 1)[1])
    except (IndexError, ValueError):
        return 0


def _batch_priority(batch: dict[str, Any]) -> tuple[int, int]:
    batch_id = str(batch.get("id") or "")
    if batch_id.startswith("sieve3_exit_level_zone_reversal_autobatch_"):
        group = 0
    elif batch_id.startswith("sieve3_exit_standard_autobatch_"):
        group = 1
    elif batch_id.startswith("sieve3_exit_pattern_autobatch_"):
        group = 2
    else:
        group = 1
    return group, _batch_number(batch_id)


def _is_pattern_source(path: Path) -> bool:
    name = path.stem.lower()
    source_name = name.split("_from_", 1)[1] if "_from_" in name else name
    return any(token in source_name for token in PATTERN_TOKENS)


def _is_level_zone_source(path: Path) -> bool:
    return path.name.startswith("sieve3_exit_level_zone_reversal_from_")


def _write_batch_file() -> list[str]:
    strategy_dir = REPO_ROOT / "user_data" / "strategies"
    files = [
        path
        for path in sorted(strategy_dir.glob("sieve3_exit_*.py"))
        if path.is_file() and _strategy_class_name(path)
    ]
    pattern_files = [path for path in files if _is_pattern_source(path)]
    # Batch groups are priority-ordered and mutually exclusive. Pattern-derived
    # level-zone files need pattern windows, so they stay in the pattern queue.
    level_zone_files = [
        path
        for path in files
        if not _is_pattern_source(path)
        and _is_level_zone_source(path)
    ]
    standard_files = [
        path
        for path in files
        if not _is_pattern_source(path)
        and not _is_level_zone_source(path)
    ]
    batches: list[dict[str, Any]] = []
    batch_ids: list[str] = []

    def add_batches(prefix: str, label_prefix: str, groups: list[list[Path]], window_mode: str) -> None:
        for index, group in enumerate(groups, start=1):
            batch_id = f"{prefix}_{index:03d}"
            batch_ids.append(batch_id)
            batches.append(
                {
                    "id": batch_id,
                    "label": f"{label_prefix} {index:03d} ({len(group)} files)",
                    "include": [path.name for path in group],
                    "exclude": [],
                    "window_mode": window_mode,
                    "description": "Autogenerated 10-file Sieve3 exit batch. Do not edit strategy code from this automation.",
                }
            )

    add_batches("sieve3_exit_level_zone_reversal_autobatch", "Sieve3 exit level-zone reversal autobatch", _chunks(level_zone_files, BATCH_SIZE), "standard")
    add_batches("sieve3_exit_standard_autobatch", "Sieve3 exit standard autobatch", _chunks(standard_files, BATCH_SIZE), "standard")
    add_batches("sieve3_exit_pattern_autobatch", "Sieve3 exit pattern autobatch", _chunks(pattern_files, BATCH_SIZE), "pattern")
    _save_json(
        BATCH_FILE,
        {
            "schema_version": 1,
            "default_batch": batch_ids[0] if batch_ids else "",
            "generated_at": datetime.now().astimezone().isoformat(),
            "batch_size": BATCH_SIZE,
            "pattern_batch_count": len(_chunks(pattern_files, BATCH_SIZE)),
            "level_zone_reversal_batch_count": len(_chunks(level_zone_files, BATCH_SIZE)),
            "standard_batch_count": len(_chunks(standard_files, BATCH_SIZE)),
            "batches": batches,
        },
    )
    return batch_ids


def _scheduled_cores(now: datetime) -> int:
    weekday = now.weekday()
    local_time = now.time()
    if weekday <= 3 and time(7, 0) <= local_time < time(19, 0):
        return LOW_POWER_CORES
    if weekday == 4 and time(7, 0) <= local_time < time(16, 0):
        return LOW_POWER_CORES
    return HIGH_POWER_CORES


def _hyperopt_jobs_for_cores(cores: int) -> str:
    return "3" if cores <= LOW_POWER_CORES else "8"


def _is_finished(status: dict[str, Any]) -> bool:
    return str(status.get("status") or "").lower() == "finished"


def _is_failed(status: dict[str, Any]) -> bool:
    return str(status.get("status") or "").lower() in {"failed", "error"}


def _read_status(job_id: str) -> dict[str, Any]:
    if not job_id:
        return {}
    return _load_json(RUNTIME_DIR / "status" / f"{job_id}.json", {})


def _read_summary(job_id: str) -> dict[str, Any]:
    if not job_id:
        return {}
    return _load_json(RUNTIME_DIR / "results" / f"{job_id}.summary.json", {})


def _has_errors(payload: dict[str, Any]) -> bool:
    try:
        return int(payload.get("error_row_count") or 0) > 0
    except (TypeError, ValueError):
        return bool(payload.get("has_error_rows"))


def _completed_autobatch_files() -> set[str]:
    completed: set[str] = set()
    for summary_path in sorted((RUNTIME_DIR / "results").glob("*entry_sieve3_exit_*.summary.json")):
        summary = _load_json(summary_path, {})
        if not _is_finished(summary) or _has_errors(summary):
            continue
        job_id = str(summary.get("job_id") or summary_path.name.replace(".summary.json", ""))
        job = _load_json(RUNTIME_DIR / "jobs" / f"{job_id}.json", {})
        for row in job.get("strategies") or []:
            if not isinstance(row, dict):
                continue
            strategy_file = str(row.get("strategy_file") or "").strip()
            if strategy_file:
                completed.add(Path(strategy_file).name)
    return completed


def _next_pending_batch(completed_files: set[str]) -> tuple[str, list[str], int, int] | tuple[None, None, int, int]:
    payload = _load_json(BATCH_FILE, {})
    batches = payload.get("batches") if isinstance(payload, dict) else []
    for index, batch in enumerate(sorted([batch for batch in batches if isinstance(batch, dict)], key=_batch_priority), start=1):
        batch_id = str(batch.get("id") or "")
        include = [str(name) for name in (batch.get("include") or []) if str(name).strip()]
        pending = [name for name in include if name not in completed_files]
        if batch_id and pending:
            return batch_id, pending, len(include), index
    return None, None, 0, 0


def _is_pattern_batch(batch_id: str) -> bool:
    return str(batch_id).startswith("sieve3_exit_pattern_autobatch_")


def _settings(batch_id: str, cores: int) -> EntrySieveSettings:
    pattern_batch = _is_pattern_batch(batch_id)
    data = {
        "preset_name": "LauncherV2-auto",
        "preset_file": "launcher_v2/runtime/entry_sieve/jobs/presets_sieve3_exit_multimetric_tmp_20260613_5pairs.json",
        "market_windows_file": "explorer/config/market_windows.json",
        "auto_window_mode": pattern_batch,
        "auto_window_count": "2" if pattern_batch else "",
        "auto_validation_window": "full_cycle_2020_2026",
        "training_windows": [] if pattern_batch else ["long_cycle_mixed_2020_2022", "long_cycle_mixed_2023_2025"],
        "validation_windows": ["full_cycle_2020_2026"],
        "epochs": "300",
        "auto_epochs": False,
        "auto_epochs_cap": "300",
        "hyperopt_jobs": _hyperopt_jobs_for_cores(cores),
        "random_state": "42,1337",
        "sampling_seed": "42,1337",
        "split_venv_pipeline": True,
        "max_cores_allowed": str(cores),
        "backtest_worker_count": str(cores),
        "strategy_batch": batch_id,
        "strategy_batch_file": str(BATCH_FILE),
        "strategy_filter": "sieve3_exit_*.py",
        "speed_run_mode": False,
        "speed_pair_count": "5",
        "speed_pairs": CORE_PAIRS,
        "normal_pair_group": "5x Core Speed Pairs",
        "normal_run_pairs": CORE_PAIRS,
        "take_profit_pct": "3",
        "stoploss_pct": "3",
        "control_entry_exits": False,
        "target_sweep_enabled": False,
    }
    allowed = {field.name for field in fields(EntrySieveSettings)}
    return EntrySieveSettings(**{key: value for key, value in data.items() if key in allowed})


def _patch_job_for_exit_hyperopt(job_path: Path) -> dict[str, Any]:
    job = _load_json(job_path, {})
    job["hyperopt_spaces"] = "sell"
    job["target_family"] = "exits"
    job["speed_run_mode"] = False
    job["speed_pairs"] = CORE_PAIRS
    job["speed_pair_count"] = "5"
    job["normal_pair_group"] = "5x Core Speed Pairs"
    job["normal_run_pairs"] = CORE_PAIRS
    job["control_entry_exits"] = False
    job["strategy_batch_label"] = f"{job.get('strategy_batch_label', job.get('strategy_batch'))} | 5 core pairs | exit MultiMetric"
    _save_json(job_path, job)
    return job


def _filter_job_to_pending_files(job_path: Path, pending_files: list[str], include_count: int) -> dict[str, Any]:
    job = _load_json(job_path, {})
    pending = {Path(name).name for name in pending_files}
    strategies = [
        row
        for row in job.get("strategies") or []
        if isinstance(row, dict) and Path(str(row.get("strategy_file") or "")).name in pending
    ]
    job["strategies"] = strategies
    if len(strategies) != include_count:
        label = str(job.get("strategy_batch_label") or job.get("strategy_batch") or "")
        job["strategy_batch_label"] = f"{label} | pending {len(strategies)}/{include_count} files"
    _save_json(job_path, job)
    return job


def _preseed_existing_results(job: dict[str, Any]) -> int:
    job_id = str(job.get("job_id") or "").strip()
    if not job_id:
        return 0
    target = RUNTIME_DIR / "results" / f"{job_id}.jsonl"
    if target.exists() and target.stat().st_size > 0:
        return 0
    strategy_names = {str(row.get("name") or "").strip() for row in job.get("strategies") or [] if isinstance(row, dict)}
    if not strategy_names:
        return 0
    seen: set[tuple[str, str, str, str]] = set()
    rows: list[str] = []
    for source_job_id in PRESEED_RESULT_JOB_IDS:
        source = RUNTIME_DIR / "results" / f"{source_job_id}.jsonl"
        if not source.exists():
            continue
        for line in source.read_text(encoding="utf-8", errors="replace").splitlines():
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if str(row.get("strategy") or "").strip() not in strategy_names:
                continue
            key = (
                str(row.get("strategy") or "").strip(),
                str(row.get("training_window") or "").strip(),
                str(row.get("random_state") or "").strip(),
                str(row.get("sampling_seed") or "").strip(),
            )
            if key in seen:
                continue
            seen.add(key)
            rows.append(line)
    if rows:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return len(rows)


def _launch_job(job_path: Path, python_exe: str) -> int:
    job = _load_json(job_path, {})
    job_id = str(job.get("job_id") or job_path.stem)
    log_dir = RUNTIME_DIR / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    stdout = (log_dir / f"{job_id}.stdout.log").open("w", encoding="utf-8", errors="replace")
    stderr = (log_dir / f"{job_id}.stderr.log").open("w", encoding="utf-8", errors="replace")
    flags = 0
    if sys.platform == "win32":
        flags = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS
    process = subprocess.Popen(
        [
            python_exe,
            "-u",
            "-m",
            "launcher_v2.services.entry_sieve_runner",
            "--job-file",
            str(job_path),
            "--resume-existing-results",
        ],
        cwd=str(APP_DIR),
        stdout=stdout,
        stderr=stderr,
        creationflags=flags,
    )
    stdout.close()
    stderr.close()
    return int(process.pid)


def run_once(*, dry_run: bool = False) -> int:
    service = EntrySieveService(APP_DIR, str(REPO_ROOT / ".venv" / "Scripts" / "python.exe"))
    active = service.live_runs()
    if active:
        print(json.dumps({"decision": "active", "active": active[:3]}, indent=2, default=str))
        return 0

    batch_ids = _write_batch_file()
    state = _load_json(STATE_FILE, {})
    if not isinstance(state, dict):
        state = {}
    state.setdefault("next_index", 0)
    state.setdefault("completed_batches", [])
    state["batch_file"] = str(BATCH_FILE)
    state["batch_count"] = len(batch_ids)

    current_job_id = str(state.get("current_job_id") or "")
    if current_job_id:
        status = _read_status(current_job_id) or _read_summary(current_job_id)
        if _is_failed(status) or _has_errors(status):
            print(json.dumps({"decision": "blocked", "reason": "previous_batch_failed", "job_id": current_job_id, "status": status}, indent=2, default=str))
            return 2
        if status and not _is_finished(status):
            print(json.dumps({"decision": "blocked", "reason": "previous_batch_not_finished_but_not_live", "job_id": current_job_id, "status": status}, indent=2, default=str))
            return 2
        if _is_finished(status):
            current_batch = str(state.get("current_batch") or "")
            completed = list(state.get("completed_batches") or [])
            if current_batch and current_batch not in completed:
                completed.append(current_batch)
            state["completed_batches"] = completed
            state["next_index"] = max(int(state.get("next_index") or 0), len(completed))
            state["current_job_id"] = ""
            state["current_batch"] = ""

    completed_files = _completed_autobatch_files()
    batch_id, pending_files, include_count, batch_index = _next_pending_batch(completed_files)
    if batch_id is None or pending_files is None:
        state["status"] = "finished"
        state["updated_at"] = datetime.now().astimezone().isoformat()
        state["completed_file_count"] = len(completed_files)
        _save_json(STATE_FILE, state)
        print(json.dumps({"decision": "finished", "batch_count": len(batch_ids)}, indent=2))
        return 0

    now = datetime.now(ZoneInfo("Europe/London"))
    cores = _scheduled_cores(now)
    settings = _settings(batch_id, cores)
    job_path = service.build_job(settings)
    job = _patch_job_for_exit_hyperopt(job_path)
    job = _filter_job_to_pending_files(job_path, pending_files, include_count)
    preseeded_rows = _preseed_existing_results(job)
    job_id = str(job.get("job_id") or job_path.stem)
    state.update(
        {
            "status": "running",
            "current_batch": batch_id,
            "current_job_id": job_id,
            "current_batch_index": batch_index,
            "next_index": max(batch_index - 1, 0),
            "last_launch_cores": cores,
            "last_launch_at": datetime.now().astimezone().isoformat(),
            "updated_at": datetime.now().astimezone().isoformat(),
            "preseeded_rows": preseeded_rows,
            "completed_file_count": len(completed_files),
            "pending_files_in_batch": len(job.get("strategies") or []),
            "source_files_in_batch": include_count,
        }
    )
    _save_json(STATE_FILE, state)
    if dry_run:
        print(json.dumps({"decision": "dry_run_launch", "batch": batch_id, "job_id": job_id, "cores": cores, "job_path": str(job_path), "preseeded_rows": preseeded_rows}, indent=2))
        return 0
    pid = _launch_job(job_path, str(REPO_ROOT / ".venv" / "Scripts" / "python.exe"))
    print(json.dumps({"decision": "launched", "batch": batch_id, "job_id": job_id, "cores": cores, "pid": pid, "job_path": str(job_path), "preseeded_rows": preseeded_rows}, indent=2))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Keep Sieve3 exit autobatches running.")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    return run_once(dry_run=bool(args.dry_run))


if __name__ == "__main__":
    raise SystemExit(main())
